// This file is automatically generated, please do not change it
// and please don't remove it from git in order not to break the uarn run:local commans
const backendVersion = "testing";
export default backendVersion;
